apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # any PVC name
  name: zarninfs-pvc
spec:
  storageClassName: nfs009
  accessModes:
  # ReadWriteMany(RW from multi nodes), ReadWriteOnce(RW from a node), ReadOnlyMany(R from multi nodes)
    - ReadWriteMany
  resources:
    requests:
       # storage size to use
      storage: 5Gi

