apiVersion: apps/v1
kind: Deployment
metadata:
  name: znwebserver
  labels:
    app: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: php-apache
        image: yenaing/php72
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hostvol
          mountPath: /var/www/html/
      volumes:
        - name: hostvol
          persistentVolumeClaim:
            # PVC name you created
            claimName: nfs9-pvc
